### PR TITLE
Changes to allow for alternate authentication fields

### PR DESCRIPTION
**Pull request by jasonhoule**
I am using LDAP for authentication. I need to authenticate against the username field rather than email address. The changes I have made use the username value set in the LoginController rather than a hard coded "email". I have also altered the structure of the javascript a little bit to accommodate this as well as allowing for other options to be set more easily, such as the "texts" values.

I have also updated the readme to reflect these changes.

### CODE REVIEW

**Comment by emredipi** [comment]
Thanks for your contribution. This look amazing but there is a problem in an important part which is the most important thing in the package. isAuth() function takes function as callback and using it if the user is still on. If session of the user is dead, after login process with login modal callback is running again.

You defined all functions in isAuth and this broke the real isAuth function and the others. Can you please check it again and PR.

**Comment by jasonhoule** [comment]
That is a good catch. I missed that but it worked as expected in my testing. I have renamed the isAuth function to isAuthenticated to avoid conflict.

**Comment by emredipi** [comment]
Hello, I checked your code. I cannot say I am good at JS but I assume that nobody can reach a function scope from outside of the function because you added all thing to isAuth function. The original isAuth (new isAuthenticated) function was there to check all process not just for form requests. I cannot call isAuthenticated from outside of isAuth. For instance, I have a delete request on a button and it triggers a AJAX request. 

```
$("[data-delete]").click(function (event) {
    event.preventDefault();
    let button=$(this);
    let href = button.attr("href");
    isAuth(function () {
      //sending DELETE request after check the auth
    });
});
```

Like this example I am using isAuth function many places (like realtime processes) not just in this package. I have to communicate with this package and call isAuth from the outside.

Like I said at first, I am not good at JS, but I know some basic things. I think we should define a class and make instance of it to use isAuth. isAuth function must be static. However, this has a bad side-effect that everybody has not last version of browsers so without ES6, it will crash. Babel solves this problem but for this little package, I think this is much. That's why I added all functions and variables as global. Do you have any advice?

**Comment by emredipi** [comment]
I merged your branch to dev branch.

**Comment by jasonhoule** [comment]
@emredipi You are correct. I made an incorrect assumption that the function was only called on form submission. My proposed solution would definitely break your delete button. I'll try to take another look at it today.

**Comment by emredipi** [comment]
I created new commit to dev branch, can you please review? I will merge with master if there is no problem.

**Comment by emredipi** [comment]
Hello @jasonhoule, have you seen my changes in dev branch?

**Comment by jasonhoule** [comment]
It looks good! I'll try to give it a try today. Thanks!

**Pull request closed without merging**
